batch_size: 128 # Batch size
num_epochs: 100 # Number of epochs for training
learning_rate: 0.0002 # Learning rate
noise_steps: 1000 # Number of steps for the reverse diffusion
beta_start: 0.0001 # Noise schedule start
beta_end: 0.02 # Noise schedule end
beta_ema: 0.9999 # Smoothing value for EMA